language: c
install: sudo apt-get -y install attr
script:
    - echo "Hello World"
    - mkdir testdir
    - setfattr -n user.myname -v "testdirexample" testdir
    - getfattr -d testdir
    - mount
    - env
    - sudo service memcached start
    - ps -ef | grep memcached
