language: c
install: sudo apt-get -y install attr
script:
    - echo "Hello World"
    - mkdir testdir
    - setfattr -n user.myname -v "testdirexample" testdir
    - getfattr -d testdir
    - mount
    - env
    - service start memcached
    - ps -ef | gre memcached
